# Related contents configuration
includeNewer = true
threshold = 40
toLower = true

[[indices]]
name = "tags"
weight = 200
cardinalityThreshold = 20

[[indices]]
name = "categories"
weight = 50

[[indices]]
name = "date"
weight = 10
pattern = "2006"
