backend:
  name: git-gateway
  branch: master
media_folder: "static/images/"
public_folder: "/images/"

collections:
  - name: "blog"
    label: Blog
    folder: "content/post"
    sort: "date: desc"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          "options":
            [
              "Humor",
              "Today I Learned",
              "Article",
              "Personal Update",
              "Quote",
              "Link",
              "Presentation",
            ],
        }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          required: false,
        }
  - name: "til"
    label: TIL
    folder: "content/post/til"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: ["Today I Learned"],
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          default: "/images/til.png",
        }
  - name: "links"
    label: Link Post
    folder: "content/post/links"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: ["Links"],
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          default: "/images/til.png",
        }
  - name: "podcast"
    label: Podcast 
    folder: "content/post/podcasts"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: ["Podcast"],
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          default: "/images/podcast.png",
        }
  - name: "base"
    label: Base 
    folder: "content/"
    create: true
    editor:
      preview: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Categories",
          name: "categories",
          widget: "hidden",
          default: ["Podcast"],
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
        }
